name: PR Checks

on:
  pull_request:
    branches:
      - main
      - alpha

jobs:
  pr_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run TypeScript, ESLint, and Prettier checks
        run: |
          pnpm typecheck
          pnpm lint
          pnpm format
          pnpm build
