name: PR Checks

on:
  pull_request:
    branches:
      - main
      - alpha

jobs:
  pr_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@4.5.3 --activate # Specify the Yarn version you're using

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable --check-cache # Immutable mode to ensure lock file consistency

      - name: Run TypeScript, ESLint, and Prettier checks
        run: |
          yarn build:engine
          yarn typecheck
          yarn lint
          yarn format
